# Generated by Django 4.1.4 on 2022-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
            ],
        ),
    ]
