# Generated by Django 4.1.4 on 2022-12-23 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919198989'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
