# Generated by Django 4.1.4 on 2022-12-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('total_price', models.FloatField(verbose_name='total_price')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuses', models.CharField(choices=[('order', 'Order'), ('kitchen', 'Kitchen'), ('ready', 'Ready'), ('serve', 'Serve')], max_length=15, verbose_name='status')),
                ('number', models.IntegerField(verbose_name='Order_number')),
                ('date', models.DateField(verbose_name='date')),
                ('reciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='orders.recipt', verbose_name='reciept')),
            ],
        ),
    ]
