# Generated by Django 4.1.4 on 2022-12-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='reciept',
        ),
        migrations.AddField(
            model_name='recipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recipt', to='orders.orders', verbose_name='order_id'),
        ),
    ]
