# Generated by Django 4.1.4 on 2022-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0001_initial'),
        ('orders', '0002_remove_orders_reciept_recipt_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_menu',
            field=models.ManyToManyField(to='menu_items.menu_item'),
        ),
    ]
