# Generated by Django 4.1.4 on 2022-12-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_order_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipt',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='orders.recipt', verbose_name='recipt_id'),
        ),
    ]
